/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // New Clinic Color Palette
        'warm-pink': {
          DEFAULT: '#D6457A',
          50: '#F4E1EA',
          100: '#ECCDDC',
          200: '#E1A5C0',
          300: '#D67DA4',
          400: '#CB5588',
          500: '#D6457A',
          600: '#B8396A',
          700: '#9A2D5A',
          800: '#7C214A',
          900: '#5E153A',
        },
        'soft-olive': {
          DEFAULT: '#DCE3D5',
          50: '#F4F6F2',
          100: '#ECF0E7',
          200: '#DCE3D5',
          300: '#CCD6C3',
          400: '#BCC9B1',
          500: '#ACBC9F',
          600: '#9CAF8D',
          700: '#8CA27B',
          800: '#7C9569',
          900: '#6C8857',
        },
        'muted-gold': {
          DEFAULT: '#C8A552',
          50: '#F5F0E1',
          100: '#EDE3C9',
          200: '#DDD099',
          300: '#CDBD69',
          400: '#C8A552',
          500: '#B8954A',
          600: '#A88542',
          700: '#98753A',
          800: '#886532',
          900: '#78552A',
        },
        'off-white': {
          DEFAULT: '#F5F6F2',
          50: '#FEFEFE',
          100: '#F5F6F2',
          200: '#EBEBEB',
          300: '#E1E1E1',
          400: '#D7D7D7',
          500: '#CDCDCD',
          600: '#C3C3C3',
          700: '#B9B9B9',
          800: '#AFAFAF',
          900: '#A5A5A5',
        },
        'light-blush': {
          DEFAULT: '#FCECF1',
          50: '#FFFFFF',
          100: '#FCECF1',
          200: '#F8D9E3',
          300: '#F4C6D5',
          400: '#F0B3C7',
          500: '#ECA0B9',
          600: '#E88DAB',
          700: '#E47A9D',
          800: '#E0678F',
          900: '#DC5481',
        },
        'charcoal': {
          DEFAULT: '#3A3A3A',
          50: '#F5F5F5',
          100: '#E8E8E8',
          200: '#DBDBDB',
          300: '#CECECE',
          400: '#C1C1C1',
          500: '#B4B4B4',
          600: '#A7A7A7',
          700: '#9A9A9A',
          800: '#8D8D8D',
          900: '#3A3A3A',
        },
        // Legacy colors (keeping for backward compatibility)
        clinic: {
          50: '#f0f9ff',
          100: '#e0f2fe', 
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#D6457A', // Updated to warm pink
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        medical: {
          50: '#f7fee7',
          100: '#ecfccb',
          200: '#d9f99d',
          300: '#bef264',
          400: '#a3e635',
          500: '#84cc16',
          600: '#DCE3D5', // Updated to soft olive
          700: '#4d7c0f',
          800: '#365314',
          900: '#1a2e05',
        }
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-in": {
          from: { transform: "translateY(-10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} 